SUPPORTED_LANGS = {
    'English': 'en',
    'Slovak': 'sk',
    'Czech': 'cs',
    'German': 'de',
    'French': 'fr',
    'Polish': 'pl',
    'Spanish': 'es',
    'Italian': 'it',
    'Hungarian': 'hu',
    'Dutch': 'nl',
    'Portuguese': 'pt',
    'Romanian': 'ro',
    'Russian': 'ru',
    'Ukrainian': 'uk',
    'Bulgarian': 'bg',
    'Croatian': 'hr',
    'Serbian': 'sr',
    'Slovenian': 'sl',
    'Greek': 'el',
    'Turkish': 'tr',
    'Arabic': 'ar',
    'Chinese (Simplified)': 'zh',
    'Japanese': 'ja',
    'Korean': 'ko'
}
